# Generated by Django 3.1.3 on 2020-11-27 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('image', models.TextField(null=True)),
                ('role', models.SmallIntegerField(choices=[(0, '教师'), (1, '学生')])),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('method', models.SmallIntegerField(choices=[(1, '自拍'), (2, '拍别人'), (3, '被别人拍'), (4, '拍老师')])),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.checkin')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photographer_id', to='manager.appuser')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_id', to='manager.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=16)),
                ('repeat', models.SmallIntegerField()),
                ('start_time', models.CharField(max_length=8)),
                ('end_time', models.CharField(max_length=8)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.course')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.course'),
        ),
    ]
